#!/bin/bash

# Walrus LinkTree - Deployment Script
# Bu script Move sözleşmesini testnet'e deploy eder

set -e

echo "🚀 Walrus LinkTree Deployment Başlıyor..."
echo ""

# Renk kodları
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# 1. Gas kontrolü
echo "1️⃣  Gas durumu kontrol ediliyor..."
GAS_OUTPUT=$(sui client gas 2>&1)
if [[ "$GAS_OUTPUT" == *"No gas coins"* ]]; then
    echo -e "${RED}❌ Gas coin yok!${NC}"
    echo ""
    echo "Lütfen faucet'ten SUI alın:"
    echo "  Discord: https://discord.gg/sui → #testnet-faucet"
    echo "  !faucet $(sui client active-address)"
    echo ""
    echo "  Web: https://suifaucet.com/"
    echo ""
    exit 1
fi
echo -e "${GREEN}✅ Gas mevcut${NC}"
echo ""

# 2. Move build
echo "2️⃣  Move sözleşmesi build ediliyor..."
cd move
sui move build
if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Build başarısız!${NC}"
    exit 1
fi
echo -e "${GREEN}✅ Build başarılı${NC}"
echo ""

# 3. Test
echo "3️⃣  Testler çalıştırılıyor..."
sui move test
if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Testler başarısız!${NC}"
    exit 1
fi
echo -e "${GREEN}✅ Testler geçti${NC}"
echo ""

# 4. Deploy
echo "4️⃣  Testnet'e deploy ediliyor..."
echo -e "${YELLOW}⏳ Bu işlem 10-30 saniye sürebilir...${NC}"
DEPLOY_OUTPUT=$(sui client publish --gas-budget 100000000 --json 2>&1)

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Deploy başarısız!${NC}"
    echo "$DEPLOY_OUTPUT"
    exit 1
fi

echo -e "${GREEN}✅ Deploy başarılı!${NC}"
echo ""

# 5. Package ID'yi parse et
PACKAGE_ID=$(echo "$DEPLOY_OUTPUT" | grep -oP '"packageId"\s*:\s*"\K[^"]+' | head -1)
echo "📦 Package ID: $PACKAGE_ID"

# 6. Registry Object ID'yi bul (SharedObjects içinden)
REGISTRY_ID=$(echo "$DEPLOY_OUTPUT" | grep -oP '"objectId"\s*:\s*"\K[^"]+' | grep -v "$PACKAGE_ID" | head -1)
echo "📋 Registry ID: $REGISTRY_ID"

# 7. .env dosyası oluştur
cd ../frontend
cat > .env << EOF
# Auto-generated by deploy script - $(date)
VITE_NETWORK=testnet
VITE_RPC_URL=https://fullnode.testnet.sui.io:443
VITE_PACKAGE_ID=$PACKAGE_ID
VITE_REGISTRY_ID=$REGISTRY_ID
VITE_WALRUS_PORTAL=trwal.app
VITE_IPFS_GATEWAY=https://ipfs.io/ipfs/
EOF

echo ""
echo -e "${GREEN}✅ .env dosyası oluşturuldu${NC}"
echo ""

# 8. Özet
echo "═══════════════════════════════════════════════════════════"
echo "🎉 DEPLOYMENT BAŞARILI!"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📝 Önemli Bilgiler:"
echo "  Package ID:  $PACKAGE_ID"
echo "  Registry ID: $REGISTRY_ID"
echo "  Network:     testnet"
echo ""
echo "🔗 Explorer Links:"
echo "  Package: https://suiscan.xyz/testnet/object/$PACKAGE_ID"
echo "  Registry: https://suiscan.xyz/testnet/object/$REGISTRY_ID"
echo ""
echo "📋 Sonraki Adımlar:"
echo "  1. Frontend'i başlat:"
echo "     cd frontend && npm run dev"
echo ""
echo "  2. Tarayıcıda aç:"
echo "     http://localhost:5173"
echo ""
echo "  3. Walrus'a deploy et:"
echo "     npm run build"
echo "     site-builder deploy ./dist --epochs 1"
echo ""
echo "═══════════════════════════════════════════════════════════"
