#!/bin/bash

echo "🚀 Deploying to Walrus Sites via manual upload..."
echo ""
echo "Build hazır: frontend/dist/"
echo ""
echo "📝 Manuel deployment adımları:"
echo ""
echo "1. Tarayıcıda https://walrus.site/ aç"
echo "2. Sui Wallet'ı bağla (testnet)"
echo "3. 'Publish Site' tıkla"
echo "4. frontend/dist klasöründeki TÜM dosyaları seç ve yükle:"
echo "   - index.html"
echo "   - assets/"
echo ""
echo "5. Epoch sayısı: 1 (test için)"
echo ""
echo "6. 'Publish' tıkla ve transaction'ı onayla"
echo ""
echo "7. Site URL'i alacaksın: https://[SITE_ID].walrus.site"
echo ""
echo "Alternatif: Github Actions ile otomatik deploy kurulabilir"
echo ""
